name: 'PaddleQACheckout'
description: 'Checkout a specific version related to PaddlePaddle from the Git repository'
inputs:
  repository:
    description: 'Repository name with owner. For example, PaddlePaddle/PaddleTest'
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
  fetch_depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    default: 1
  submodules:
    description: >
      Whether to checkout submodules: `true` to checkout submodules or `recursive` to
      recursively checkout submodules.
    default: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.ref }}
    - ${{ inputs.path }}
    - ${{ inputs.fetch-depth }}
    - ${{ inputs.submodules }}

